name: gha-migration/depends_practice

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "Docker Image Build Successful" > build.txt

      - run: cat build.txt

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build.txt
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build
          path: .

      - run: echo "Reading artifact from build stage"

      - run: cat build.txt

      - run: echo "Tests Passed" > test.txt

      - uses: actions/upload-artifact@v4
        with:
          name: test
          path: test.txt
          retention-days: 1

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: test
          path: .

      - run: echo "Deploying application"

      - run: cat test.txt
